export const LOGIN = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
};

export const GET_LIST_IMAGE = {
  GET_LIST_IMAGE_START: "GET_LIST_IMAGE_START",
  GET_LIST_IMAGE_SUCCESS: "GET_LIST_IMAGE_SUCCESS",
  GET_LIST_IMAGE_FAIL: "GET_LIST_IMAGE_FAIL",
};

export const COLLECTION = {
  GET_LIST_COLLECTION_SUCCESS: "GET_LIST_COLLECTION_SUCCESS",
  GET_LIST_COLLECTION_FAIL: "GET_LIST_COLLECTION_FAIL",
  CREATE_COLLECTION_SUCCESS: "CREATE_COLLECTION_SUCCESS",
  CREATE_COLLECTION_FAIL: "CREATE_COLLECTION_FAIL",
  DELETE_COLLECTION_SUCCESS: "DELETE_COLLECTION_SUCCESS",
  DELETE_COLLECTION_FAIL: "DELETE_COLLECTION_FAIL",
  UPDATE_COLLECTION_INFOR_SUCCESS: "UPDATE_COLLECTION_INFOR_SUCCESS",
  UPDATE_COLLECTION_INFOR_FAIL: "UPDATE_COLLECTION_INFOR_FAIL",
  ADD_IMAGE_TO_COLLECTION_SUCCESS: "ADD_IMAGE_TO_COLLECTION_SUCCESS",
  ADD_IMAGE_TO_COLLECTION_FAIL: "ADD_IMAGE_TO_COLLECTION_FAIL",
  DELETE_IMAGE_FROM_COLLECTION_SUCCESS: "DELETE_IMAGE_FROM_COLLECTION_SUCCESS",
  DELETE_IMAGE_FROM_COLLECTION_FAIL: "DELETE_IMAGE_FROM_COLLECTION_FAIL",
};
