export const LOGIN = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
};

export const GET_LIST_IMAGE = {
  GET_LIST_IMAGE_START: "GET_LIST_IMAGE_START",
  GET_LIST_IMAGE_SUCCESS: "GET_LIST_IMAGE_SUCCESS",
  GET_LIST_IMAGE_FAIL: "GET_LIST_IMAGE_FAIL",
};
